### ISSUE TITLE
bottom menus dont adjust height when group expanded

### ISSUE THREAD

**Issue by syonfox** [syonfox/leaflet-panel-layers#11]
this may be a bug with leaflet control and I and find quick solutions It seems to be caused by the position of the menu not being updated when a group is expanded. it only effects bottom menus
![image](https://user-images.githubusercontent.com/9345677/61909484-2270b180-aee7-11e9-9452-ff749bc4ece7.png)

**Comment by veragreen119** [comment]
I'm pretty sure this is fixed now through setting the max height parameter.
