### ISSUE TITLE
Tooltip Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by LorrnelGroup** [syonfox/leaflet-panel-layers#12]
Uncaught TypeError: Cannot read property '0' of undefined
    at HTMLDivElement.tooltipMouseover (leaflet-panel-layers.js:261)
    at HTMLDivElement.r (leaflet.js:5)

**Comment by syonfox** [comment]
370939bdf3f2f2a5b696d2f41437fe9b4a41e0a9
I added a few checks to handle the exceptions and removed the debug logs as well.
