### ISSUE TITLE
Set default for groups expanded or colapsed

### ISSUE THREAD

**Issue by veragreen119** [syonfox/leaflet-panel-layers#14]
When adding layers dynamically to groups allow the user to still control if the layer group is collapsed or expanded on reload.  Add this setting to the default startup settings?

**Comment by veragreen119** [comment]
This can be resolved by adding "true" as the last parameter when adding a layer:
`over1.addOverlay({layer: layerName, tooltip: layerDescriptionText}, 'Layer Title','GroupName', true);`
where over1 is:
`var over1 = L.control.panelLayers(...)`

Would be nice to have a more global solution.

**Comment by syonfox** [comment]
I just added some functions see the readme for the methods but basic usage would be 
```
over1.expandGroup('group name');
over1.collapseGroup('group name');
```

**Comment by syonfox** [comment]
... didint mean to close this yet ... if this is not what you want reopen please
