### ISSUE TITLE
Layer Tree Off Page: Scroll bar/ToolTip Conflict

### ISSUE THREAD

**Issue by veragreen119** [syonfox/leaflet-panel-layers#16]
Looking at this example:
https://portaldev.lorrnel.com/landMap/index.html

When all of the layers are expanded they extend bellow the page. The plugin will need to add a scroll bar when this occurs.

**Comment by veragreen119** [comment]
Solved short term by starting with all groups collapsed.
As discussed there is a conflict between the scroll bar and the tool tips. For now we can:
- add the scroll bar
- alter the tool tips so that they display inline under the layer
- add a longer delay to tool tips so the user has to hover longer to get the tool tip.

Will see how that works out.

**Comment by veragreen119** [comment]
Fixes to the last implementation:
[For Testing](https://portaldev.lorrnel.com/landMap_kl/index.html)

- prevent the items from expanding on hover indefinitely making the containers very long
![image](https://user-images.githubusercontent.com/40037166/67401900-04116500-f56d-11e9-84c7-a6711b943688.png)

- the ON hover timing looks pretty good. try to DECREASE the OFF hover timing.
- make the original container small like in the original solution


![image](https://user-images.githubusercontent.com/40037166/67401775-d88e7a80-f56c-11e9-95fa-a775b2ff7521.png)

**Comment by syonfox** [comment]
Fixed as of latest commit see updated version working in [landmap_kl](https://portaldev.lorrnel.com/landMap_kl/index.html)
