### ISSUE TITLE
RemoveLayer

### ISSUE THREAD

**Issue by veragreen119** [syonfox/leaflet-panel-layers#18]
Using this base code: [SDV Testing (Kier)](https://portaldev.lorrnel.com/landMap_kl/index.html)
SDV = Spatial Data Viewer
The Remove button is suposed to remove the layer from the map and the panel.  The button function (search for "ulRemove") is at line 653.

Please figure out how to remove the layer from the layer tree.

[Uploading powerlines.zip…]()

**Comment by syonfox** [comment]
Solved you can find a layer by name in leaflet panel layers and remove it using removeLayer()
```
    var ulLayerName = document.getElementById("select1_ulStyle").value;
    l = over1._layers.find(item=>item.name==ulLayerName);
    over1.removeLayer(l);
```
There is still a bug where when you remove the layer it doesn't remove from the drop down properly also if you remove the last layer it should hide the menu.

[landmap_kl](https://portaldev.lorrnel.com/landMap_kl/index.html)

**Comment by veragreen119** [comment]
Sounds good. To remove from the drop down we just need to remove the item from the lists. I can do this.
