### ISSUE TITLE
Panel Does Not Detect Max Map Height

### ISSUE THREAD

**Issue by veragreen119** [syonfox/leaflet-panel-layers#2]
When the panel length exceeds the map height the panel does not correctly respect the total map height.  Although the bottom most layer can actually be seen the user is not aware that the bottom of the panel has been reached because the bottom is not shown.  Also any map controls below the panel are not accessible to the user.
**Proposed Solution:** 

- add a feature to collapse all groups (short term solution that doesn't actually fix the issue but will make the map usable)

- add the feature to collapse the entire panel (also short term solution that doesn't actually fix the issue but will make the map usable)

- actually fix the issue by altering the parameter that determines the max available height and reducing it from it's current setting.

![image](https://user-images.githubusercontent.com/40037166/57740919-62115680-7677-11e9-8225-d2ecbe058664.png)

**Comment by veragreen119** [comment]
PS - this is NOT caused by the bootstrap css - happens without those changes as well.

**Comment by syonfox** [comment]
This does not appear to need fixing there is already a option compactOffset option to fix this.  the default is 0 I could change this to 30 which would look ok by default but i suspect the intended use is to use4 this to change the max height of panels if you want to leave space for another control object bellow the panel you can increase this number

**Comment by veragreen119** [comment]
You are correct.  Can fix this with compactOffset so you can mark as closed. thanks.

**Comment by veragreen119** [comment]
After further review this works if there is only one panel but when there are multiple panels only the top most panel functions as it should.  The second panel is not aware that there is another panel (assuming not correctly assuming it's starting Y location) and therefore does not position itself correctly.  
In this image when the Layers panel is on TOP of the backgrounds panel it works as it should but when it is below it does not.
Low priority because I can for now just have one panel.

![image](https://user-images.githubusercontent.com/40037166/57808615-fa174a80-7720-11e9-8123-68af80a536c0.png)

**Comment by syonfox** [comment]
@veragreen119 do you have a demo sight that i can look at for this?

**Comment by veragreen119** [comment]
This is resolved by setting the following parameters:
```
    compact: true,//panle will take up only space needed instead of page height
    compactOffset:150, //map.getSize.y/2
```
