### ISSUE TITLE
Panel and Group Icon

### ISSUE THREAD

**Issue by veragreen119** [syonfox/leaflet-panel-layers#4]
Enable the panel and group to have an icon.

- Panel Icon - enable the Panel to have an Icon in addition to the title (same as allowed for layers). Icon will appear at "1" in the screenshot before the title.

- Group Icon - enable the Group to have an Icon in addition to the title (same as allowed for layers) . Icon will appear at "2" in the screenshot before the title and checkbox.

![image](https://user-images.githubusercontent.com/40037166/57742882-0dbea480-7680-11e9-911d-5bca49debdb9.png)

**Comment by syonfox** [comment]
@veragreen119 would you want to be able to set the + - icons like for panel collapsing or have a secondary icon like described above?
