### ISSUE TITLE
selecting/deselecting group option

### ISSUE THREAD

**Issue by veragreen119** [syonfox/leaflet-panel-layers#5]
Make the functionality you added for selecting/deselecting everything in a group as an optional property.  Add groupCheckboxes (panel level) OR groupCheckbox (group level)  as an option. I would say chose whichever is easier to implement.  This is implemented in this other module at what for us would be the panel level.
[https://github.com/ismyrnow/leaflet-groupedlayercontrol](url)
```
// Show a checkbox next to non-exclusive group labels for toggling all
  groupCheckboxes: true
```
So at the end you would either have an additional option for the panel:
```
                var over1 = L.control.panelLayers(overLayers.layers, null,  {
                    title: 'My Data',
                    position: 'topleft',
                    compact: true,
                    collapsibleGroups: true,
                    groupCheckboxes: true, //NEW
                    collapsed: false
                });
```
OR for each group:
```
                        layers: [
                            {
                                group: "Group 1",
                                collapsed: true,
                                groupCheckbox: true, //NEW
                                layers: []
                            },
```

**Comment by syonfox** [comment]
This was done in a previous commit but not closed
