### ISSUE TITLE
leaflet-panel-layers.css Updates

### ISSUE THREAD

**Issue by veragreen119** [syonfox/leaflet-panel-layers#6]
Just two small changes - please merge into main code so I don't have to re-write it when I pull a new version.  Haven't figured out the Pull request yet . . . 
added line 52:

```
.leaflet-panel-layers-icon {
	text-align: center;
	float: left;
    padding-right: 25px;/*adding padding here creates some space between the icon and the label*/
}
```

Changed one of these from right to left so that the check box is on the left of the title, can't remember which one:

```
.leaflet-panel-layers-base .leaflet-panel-layers-selector {
	float: left;
}
.leaflet-panel-layers-overlays .leaflet-panel-layers-selector {
	float: left;
}
.leaflet-panel-layers.expanded .leaflet-panel-layers-overlays input {
	display: block;
}
.leaflet-control-layers-selector {
	float: left;
}
```

[leaflet-panel-layers.zip](https://github.com/syonfox/leaflet-panel-layers/files/3180590/leaflet-panel-layers.zip)

**Comment by syonfox** [comment]
Is this what you want? I can move the group check box over as well if so.
![image](https://user-images.githubusercontent.com/9345677/57793351-f8845d00-76f5-11e9-9f9d-53b255578acc.png)


I think it is nicer reading from left to right so you see the icon the name and whether its on or not.  Here i moved the radio buttons to the left as well but the original also makes sense for those
![image](https://user-images.githubusercontent.com/9345677/57793728-de974a00-76f6-11e9-8e72-3446137f9b34.png)

**Comment by veragreen119** [comment]
Yeah when the box gets wider because some titles are long I think it is better to have all of the check boxes on the left.  Mostly because the collapse/expand icon is on the left it is annoying to have to mouse back and forth.
![image](https://user-images.githubusercontent.com/40037166/57794904-f922f080-7701-11e9-97c7-cfc31dab9ff7.png)
