### ISSUE TITLE
leaflet-panel-layers-glyphicons.css

### ISSUE THREAD

**Issue by veragreen119** [syonfox/leaflet-panel-layers#7]
So when people use these plugins they generally just take all the src folder content to include in their script.  I won't pretend to know the correct way to do things but I suggest moved your glyphicons.css from examples to src and renaming it to leaflet-panel-layers-glyphicons.css

Then in the documentation we need to specify that the leaflet-panel-layers-glyphicons.css has to be called BEFORE leaflet-panel-layers.css and AFTER bootstrap.

**Comment by syonfox** [comment]
Done
