### ISSUE TITLE
Layer Abstract

### ISSUE THREAD

**Issue by LorrnelGroup** [syonfox/leaflet-panel-layers#9]
This is a feature request for adding an abstract to layers in the layer panel.  The goal is for the user to get additional information such as a short paragraph of test describing the dataset about a layer.  This could be implemented through adding a small question mark or "i" icon to each layer which would display a popup when the user either clicks or hovers over it.  Hover functionality is preferd.

**Comment by veragreen119** [comment]
Sample abstract:

The Municipal District dataset is comprised of all the polygons that represent Municipal Districts in Alberta. Municipal District is a municipality type defined under the authority of the Municipal Government Act. The formation of a Municipal District occur when a majority of the buildings used as dwellings are on parcels of land with an area of at least 1850 square meters and there is a population of 1000 or more. A municipal district is a government form in rural areas of the province.

I put this sample abstract into the "parking" layer tool tip in your example and it is cut off.  So you need to look into the tool tip properly resizing to accept a larger text block.  I do like the idea of the tool tip showing to the side.

**Comment by LorrnelGroup** [comment]
I am already using L.Control.BootstrapModal in the map but not sure if that can be adapted.

[https://github.com/gregallensworth/L.Control.BootstrapModal](url)

**Comment by LorrnelGroup** [comment]
Not sure if this would be too much of a stretch to adapt:
[https://github.com/yafred/leaflet-responsive-popup](url)

**Comment by syonfox** [comment]
This is now mostly implemented I will close it if it is good and we can create new issues for bugs with the tooltips or reopen this issue
